import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Task,Locale} from './types';
interface Review {jobId:string;changes:{path:string;baseline:string;before:string|null;after:string|null;verified:boolean}[];checks:{check_id:string;outcome:string;evidence:'agent_reported'}[];workspace:{root:string;branch:string;head:string};scope:string}
interface Target {root:string;branch:string;head:string;digest:string}
interface Launch {prompt:string;workspace:string;product:string}
interface Handoff {guidance:string;readiness:string;variant_id:string;workspace:string;connect_context:{origin:string;task_id:string;product:string}}
export function HarnessApplication({task,locale,busy,onAction}:{task:Task;locale:Locale;busy:boolean;onAction:(action:string,input?:unknown)=>Promise<void>}){
 const app=task.application!;const t=(en:string,ko:string)=>locale==='ko'?ko:en;
 const [workspace,setWorkspace]=useState(app.workspace??'');const [product,setProduct]=useState(app.product??'codex');const [target,setTarget]=useState<Target|null>(null);
 const [review,setReview]=useState<Review|null>(null);const [launch,setLaunch]=useState<Launch|null>(null);const [handoff,setHandoff]=useState<Handoff|null>(null);const [error,setError]=useState<string|null>(null);const [open,setOpen]=useState(false);
 const canPrepare=task.actions.find(action=>action.code==='application-prepare')?.enabled===true;
 const canUseApplyingContext=['awaiting_session','applying'].includes(app.state);
 const canRetryPreparation=task.actions.find(action=>action.code==='prepare')?.enabled===true;
 const capability=app.capabilities.find(c=>c.id===product);
 useEffect(()=>{const controller=new AbortController();const refresh=async()=>{
  setReview(null);setLaunch(null);setHandoff(null);
  if(!app.jobId)return;
  const read=async<T,>(endpoint:string):Promise<T|null>=>{const response=await fetch(`/api/tasks/${task.id}/${endpoint}`,{cache:'no-store',signal:controller.signal});return response.ok?await response.json() as T:null;};
  try{const [nextLaunch,nextReview,nextHandoff]=await Promise.all([canUseApplyingContext?read<Launch>('application-launch-context'):Promise.resolve(null),read<Review>('application-review'),read<Handoff>('application-handoff')]);if(!controller.signal.aborted){setLaunch(nextLaunch);setReview(nextReview);setHandoff(nextHandoff);if(app.state==='applied')setOpen(true);}}catch{if(!controller.signal.aborted)setError(t('Refresh to inspect the current application state.','현재 적용 상태를 보려면 새로고침하세요.'));}
 };const timer=setTimeout(()=>{void refresh();},0);return()=>{controller.abort();clearTimeout(timer);};},[task.id,task.version,app.jobId,app.state,locale,canUseApplyingContext]);
 const inspect=async()=>{setError(null);try{const response=await fetch(`/api/tasks/${task.id}/application-workspace?directory=${encodeURIComponent(workspace)}`,{cache:'no-store'});if(!response.ok)throw new Error();setTarget(await response.json() as Target);}catch{setTarget(null);setError(t('Choose a checkout or worktree of the registered repository.','등록된 저장소의 checkout 또는 worktree를 선택하세요.'));}};
 const copy=(text:string)=>{void navigator.clipboard.writeText(text).catch(()=>setError(t('Select and copy the text manually.','텍스트를 선택하여 직접 복사하세요.')));};
 return <Card><CardHeader><CardTitle>{t('Apply the assigned harness','배정된 하네스 적용')}</CardTitle><p role="status">{task.preparation.assigned_variant_id??t('Assignment pending','배정 대기')} · {app.state}</p></CardHeader><CardContent className="space-y-5">
 <p>{t('A fresh native agent adapts the assigned procedure and edits the selected workspace. Decide file and command permissions in the native window.','새 네이티브 세션의 에이전트가 배정된 절차를 프로젝트에 맞게 적용하고 선택한 작업 공간을 직접 수정합니다. 파일·명령 권한은 네이티브 창에서 결정하세요.')}</p>
 {app.state==='blocked_configuration'&&<div className="space-y-3"><p>{t('Resolve the configuration blocker, then retry preparation for this same task. Native application becomes available after preparation; no legacy configuration is applied here.','구성 문제를 해결한 뒤 같은 작업의 준비를 재시도하세요. 준비가 완료되면 네이티브 적용을 진행할 수 있습니다.')}</p><Button variant="outline" disabled={busy||!canRetryPreparation} onClick={()=>{void onAction('prepare');}}>{t('Retry same task preparation','같은 작업 준비 재시도')}</Button></div>}
 {app.state==='abandoned'&&<p>{t('This applying context has expired. Inspect the target and prepare a new context to retry. Existing edits remain.','이 적용 문맥은 만료되었습니다. 대상을 확인하고 새 문맥을 준비해 재시도하세요. 기존 변경은 유지됩니다.')}</p>}
 {canPrepare&&<div className="space-y-3"><Label htmlFor="application-target">{t('Existing checkout / worktree','기존 checkout / worktree')}</Label><Input id="application-target" value={workspace} onChange={event=>{setWorkspace(event.target.value);setTarget(null);}}/><Button variant="outline" disabled={busy} onClick={()=>{void inspect();}}>{t('Inspect target','대상 확인')}</Button>
 <Label htmlFor="application-product">{t('Native product','네이티브 제품')}</Label><select id="application-product" className="rounded border p-2" value={product} onChange={event=>setProduct(event.target.value)}>{app.capabilities.map(c=><option key={c.id} value={c.id}>{c.product}{c.available?'':t(' · copy guidance',' · 복사 안내')}</option>)}</select>
 {target&&<p className="break-all text-sm">{target.root} · {target.branch||t('Detached HEAD','분리된 HEAD')} · {target.head}</p>}
 <Button disabled={busy||!target||workspace!==target.root} onClick={()=>{if(target)void onAction('application-prepare',{workspace:target.root,workspaceDigest:target.digest,product});}}>{t('Prepare native session context','네이티브 세션 문맥 준비')}</Button></div>}
 {app.workspace&&<p className="break-all text-sm">{app.workspace}</p>}
 {canUseApplyingContext&&launch&&<div className="space-y-3"><p>{t('macOS Terminal interactive CLI opening is available when the CLI is installed. Actual native acceptance remains unverified. Opening acknowledgement is not evidence that an agent started.','CLI가 설치된 macOS에서는 Terminal의 인터랙티브 CLI 열기를 요청할 수 있습니다. 실제 네이티브 수용 검증은 아직 남아 있으며, 열기 응답은 에이전트 시작 증거가 아닙니다.')}</p>
 {app.state==='awaiting_session'&&<Button disabled={busy||!app.capabilities.find(c=>c.id===launch.product)?.available||app.launchState!=='not_requested'} onClick={()=>{void onAction('application-open');}}>{t('Open fresh native session','새 네이티브 세션 열기')}</Button>}
 <p>{app.launchState} · {capability?.reason}</p><p>{t('If automatic opening is unavailable or fails, open a fresh session in the target yourself and paste this context. Preserve the stored assignment.','자동 열기를 사용할 수 없거나 실패하면 대상에서 새 세션을 직접 열고 아래 문맥을 붙여 넣으세요. 저장된 배정을 유지합니다.')}</p><textarea readOnly aria-label={t('Application context','적용 문맥')} className="w-full rounded border p-3 font-mono text-xs" rows={5} value={launch.prompt}/><Button variant="outline" onClick={()=>copy(launch.prompt)}>{t('Copy application context','적용 문맥 복사')}</Button></div>}
 {review&&<div className="space-y-3"><h3>{t('Actual file changes after application','적용 후 실제 파일 변경')}</h3><p>{t('Only reported files are verified. Commands and scripts are agent reported, not independently observed.','보고된 파일만 검증합니다. 명령·스크립트 결과는 에이전트 보고이며 독립적으로 관찰한 실행 증거가 아닙니다.')}</p>{review.checks.length?review.checks.map(check=><p key={check.check_id}>{check.check_id} · {check.outcome} · {check.evidence}</p>):<p>{t('Verification checks missing','검사 결과 없음')}</p>}
 {review.changes.map(change=><details key={change.path} className="rounded border p-3"><summary>{change.path} · {change.verified?t('hash verified','해시 검증됨'):t('file drift','파일 변경됨')} · {change.baseline}</summary><div className="grid gap-3 md:grid-cols-2"><pre className="overflow-auto whitespace-pre-wrap text-xs">{change.before??t('(absent, binary, or missing baseline)','(기존 파일 없음·바이너리·기준 없음)')}</pre><pre className="overflow-auto whitespace-pre-wrap text-xs">{change.after??t('(absent or binary)','(파일 없음·바이너리)')}</pre></div></details>)}</div>}
 {app.jobId&&['awaiting_session','applying','applied','failed'].includes(app.state)&&<div><p>{t('Abandoning invalidates this attempt. Stop the external agent in its native window; existing edits remain.','적용 포기는 이 시도를 무효화합니다. 외부 에이전트는 네이티브 창에서 중지하세요. 이미 바뀐 파일은 유지됩니다.')}</p><Button variant="outline" disabled={busy} onClick={()=>{void onAction('application-cancel');}}>{t('Abandon attempt','적용 시도 포기')}</Button></div>}
 {app.state==='applied'&&handoff&&<Button variant="outline" onClick={()=>setOpen(true)}>{t('New working-session guidance','새 실제 작업 세션 안내')}</Button>}
 {app.reason&&<p>{app.reason}</p>}{error&&<p role="alert">{error}</p>}
 <Dialog open={open&&app.state==='applied'&&!!handoff} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{t('Start a separate working session','별도 실제 작업 세션 시작')}</DialogTitle><DialogDescription>{t('File verification, instruction loading, and measurement readiness are separate facts.','파일 검증·지침 로딩·측정 준비 상태는 별도 사실입니다.')}</DialogDescription></DialogHeader>{handoff&&<><p className="break-all">{handoff.variant_id} · {handoff.workspace}</p><p>{handoff.readiness}</p><textarea readOnly aria-label={t('Working-session handoff','작업 세션 전달 안내')} className="w-full rounded border p-3 text-xs" rows={6} value={handoff.guidance}/><Button onClick={()=>copy(handoff.guidance)}>{t('Copy working-session guidance','작업 세션 안내 복사')}</Button></>}</DialogContent></Dialog>
 </CardContent></Card>;
}
