import {fileURLToPath} from 'node:url';
import {existsSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {join,resolve,dirname,basename} from 'node:path';
import {lstatSync,realpathSync} from 'node:fs';
import {z} from 'zod';
import type {Store} from './store.js';
import {IdSchema} from './contracts.js';
import {canonicalJson,hashBytes,readHarness,readRepositoryFile,readStrictJson} from './harness-config.js';
import {assertApplicationWorkspace,inspectApplicationWorkspace} from './harness-application-workspace.js';
import {applicationPath,durablePrivateBytes,optionalApplicationBytes,outputDigest} from './harness-application-files.js';
import {ApplicationContextSchema,ApplicationSelectionSchema,ApplicationCheckpointSchema,ApplicationReportSchema,applicationHash,type ApplicationSelection} from './harness-application-contract.js';
import {getApplicationLaunchCapability,openApplicationSession,type LaunchEnvironment} from './harness-application-launch.js';
import type {VerifiedSessionIdentity} from './session-binding-contract.js';
const procedureSchema=z.strictObject({origin:z.string(),bundlePath:z.string(),bundleHash:applicationHash,common:z.array(z.strictObject({path:z.string(),hash:applicationHash})).optional()});
const checkpointSchema=z.strictObject({path:z.string(),before_hash:applicationHash.nullable(),before_file:z.string().nullable()});
const resultSchema=z.strictObject({outputs:z.array(z.strictObject({path:z.string(),sha256:applicationHash.nullable(),checkpoint_id:z.string().nullable()})),checks:z.array(z.strictObject({check_id:z.string(),outcome:z.enum(['passed','failed','missing','refused']),evidence:z.literal('agent_reported')})),report_hash:applicationHash});
type Marker={task_id:string;project_id:string;input_hash:string;current_job:string|null;epoch:number};
type Attempt={id:string;task_id:string;state:string;context_hash:string;result_hash:string|null;epoch:number;completed_at:string|null;reason_code:string|null;launch_state:string;identity_hash:string|null};
type Checkpoint={id:string;attempt_id:string;before_hash:string|null;record_hash:string};
const privatePath=(taskId:string)=>`.harness-delta/applications/${IdSchema.parse(taskId)}`;
function projectRoot(store:Store,projectId:string):string {const root=store.get<{local_root:string}>('SELECT local_root FROM projects WHERE id=?',[projectId])?.local_root;if(!root)throw new Error('unknown_project');return root;}
export function applicationRequired(store:Store,taskId:string):boolean{return !!store.get("SELECT 1 FROM harness_application_tasks WHERE task_id=? UNION ALL SELECT 1 FROM tasks WHERE id=? AND application_mode='agent_applied'",[taskId,taskId]);}
function marker(store:Store,taskId:string):Marker {
 const row=store.get<Marker>('SELECT * FROM harness_application_tasks WHERE task_id=?',[IdSchema.parse(taskId)]);
 if(!row)throw new Error('application_required');
 if(store.get("SELECT 1 FROM tombstones WHERE (kind='task' AND id=?) OR (kind='project' AND id=?)",[taskId,row.project_id]))throw new Error('deleted_identifier');
 return row;
}
function loadProcedure(store:Store,row:Marker){const origin=projectRoot(store,row.project_id);const bytes=readRepositoryFile(origin,`${privatePath(row.task_id)}/procedure.json`);if(hashBytes(bytes)!==row.input_hash)throw new Error('application_input_changed');const procedure=procedureSchema.parse(readStrictJson(bytes));if(procedure.origin!==origin||readHarness(origin,procedure.bundlePath).bundle_hash!==procedure.bundleHash)throw new Error('application_input_changed');return procedure;}
export function requireApplication(store:Store,taskId:string,input:z.infer<typeof procedureSchema>):void {
 const procedure=procedureSchema.parse(input);const task=store.get<{project_id:string}>('SELECT project_id FROM tasks WHERE id=?',[taskId]);if(!task)throw new Error('unknown_task');
 if(projectRoot(store,task.project_id)!==procedure.origin||readHarness(procedure.origin,procedure.bundlePath).bundle_hash!==procedure.bundleHash)throw new Error('application_input_changed');
 const bytes=Buffer.from(JSON.stringify(procedure));const inputHash=hashBytes(bytes);const old=store.get<Marker>('SELECT * FROM harness_application_tasks WHERE task_id=?',[taskId]);
 if(old){if(old.input_hash!==inputHash)throw new Error('application_input_changed');loadProcedure(store,marker(store,taskId));return;}
 if(store.get("SELECT 1 FROM tombstones WHERE (kind='task' AND id=?) OR (kind='project' AND id=?)",[taskId,task.project_id]))throw new Error('deleted_identifier');
 if(applicationRequired(store,taskId))throw new Error('application_required');
 // Reserve first: interrupted private writes keep the task fenced.
 store.immediateTransaction(()=>{store.execute("UPDATE tasks SET application_mode='agent_applied' WHERE id=?",[taskId]);store.execute('INSERT INTO harness_application_tasks(task_id,project_id,input_hash) VALUES(?,?,?)',[taskId,task.project_id,inputHash]);});
 durablePrivateBytes(procedure.origin,`${privatePath(taskId)}/procedure.json`,bytes);
}
function current(store:Store,taskId:string){
 const row=marker(store,taskId),procedure=loadProcedure(store,row);
 const attempt=row.current_job?store.get<Attempt>('SELECT * FROM harness_application_attempts WHERE id=? AND task_id=?',[row.current_job,taskId]):undefined;
 if(!attempt)throw new Error('application_required');
 const directory=`${privatePath(taskId)}/${attempt.id}`,bytes=readRepositoryFile(procedure.origin,`${directory}/context.json`);
 if(hashBytes(bytes)!==attempt.context_hash)throw new Error('application_input_changed');
 const context=ApplicationContextSchema.parse(readStrictJson(bytes));
 if(context.attempt_id!==attempt.id||context.task_id!==taskId||context.project_id!==row.project_id||context.bundle_hash!==procedure.bundleHash||context.bundle_path!==procedure.bundlePath||context.epoch!==attempt.epoch)throw new Error('application_input_changed');
 assertApplicationWorkspace(context.workspace);
 const assignment=store.get<{variant_id:string}>('SELECT variant_id FROM comparison_assignments WHERE task_id=?',[taskId]);
 if(assignment?.variant_id!==context.variant_id)throw new Error('application_input_changed');
 return {row,procedure,attempt,context,directory};
}
function owned(store:Store,data:ReturnType<typeof current>){if(store.get<{task_id:string}>('SELECT task_id FROM external_surface_leases WHERE surface_key=?',[hashBytes(data.context.workspace.root)])?.task_id!==data.row.task_id)throw new Error('application_surface_unowned');}
function resultFor(data:ReturnType<typeof current>){if(!data.attempt.result_hash)throw new Error('application_required');const bytes=readRepositoryFile(data.procedure.origin,`${data.directory}/result.json`);if(hashBytes(bytes)!==data.attempt.result_hash)throw new Error('application_output_changed');return resultSchema.parse(readStrictJson(bytes));}
function verifyFiles(data:ReturnType<typeof current>){const result=resultFor(data);for(const output of result.outputs)if(outputDigest(data.context.workspace.root,output.path)!==output.sha256)throw new Error('application_output_changed');return result;}
export function effectiveTaskWorkspace(store:Store,taskId:string){if(applicationRequired(store,taskId))return current(store,taskId).context.workspace.root;const task=store.get<{project_id:string}>('SELECT project_id FROM tasks WHERE id=?',[taskId]);if(!task)throw new Error('unknown_task');return projectRoot(store,task.project_id);}
export function assertAppliedHarness(store:Store,taskId:string){const data=current(store,taskId);if(data.attempt.state!=='applied'||!data.attempt.completed_at||data.attempt.epoch!==data.row.epoch)throw new Error('application_required');owned(store,data);const result=verifyFiles(data);if(!result.checks.length||result.checks.some(check=>check.outcome!=='passed'))throw new Error('application_checks_incomplete');}
const identityHash=(product:string,id:string)=>hashBytes(JSON.stringify([product,id]));
export function assertApplicationWorkingIdentity(store:Store,taskId:string,identity:{product:string;sessionId:string;parentSessionId:string|null;createdAt:string}){
 const rootHash=identityHash(identity.product,identity.sessionId),parentHash=identityHash(identity.product,identity.parentSessionId??identity.sessionId);
 if(store.get('SELECT 1 FROM harness_application_exclusions WHERE identity_hash=? OR identity_hash=? UNION ALL SELECT 1 FROM harness_application_roles WHERE identity_hash=? OR identity_hash=? UNION ALL SELECT 1 FROM harness_application_setup_sessions WHERE identity_hash=? OR identity_hash=?',[rootHash,parentHash,rootHash,parentHash,rootHash,parentHash]))throw new Error('application_setup_session_excluded');
 if(!applicationRequired(store,taskId))return;assertAppliedHarness(store,taskId);const data=current(store,taskId);
 if(!data.attempt.identity_hash)throw new Error('application_identity_unavailable');
 if(!Number.isFinite(Date.parse(identity.createdAt))||Date.parse(identity.createdAt)<=Date.parse(data.attempt.completed_at!))throw new Error('application_fresh_session_required');
 const old=store.get<{epoch:number}>('SELECT epoch FROM harness_application_session_epochs WHERE session_id=? AND task_id=?',[identity.sessionId,taskId]);if(old&&old.epoch!==data.row.epoch)throw new Error('application_epoch_changed');
}
export function bindApplicationEpoch(store:Store,taskId:string,sessionId:string){if(applicationRequired(store,taskId)){assertAppliedHarness(store,taskId);store.execute('INSERT OR IGNORE INTO harness_application_session_epochs(session_id,task_id,epoch) VALUES(?,?,?)',[sessionId,taskId,marker(store,taskId).epoch]);}}
export function prepareApplicationWorkingContext(store:Store,taskId:string){assertAppliedHarness(store,taskId);const data=current(store,taskId),result=resultFor(data);const rules=result.outputs.filter(file=>basename(file.path)==='AGENTS.md'&&file.sha256!==null).map(file=>({path:file.path,sha256:file.sha256!,content:readRepositoryFile(data.context.workspace.root,file.path).toString('utf8')}));const content=canonicalJson({schema_version:2,mode:'agent_applied',scope:'Apply each rule in its directory and descendants.',rules});return {workspace:data.context.workspace.root,epoch:data.row.epoch,procedureBundleHash:data.procedure.bundleHash,outputManifestHash:data.attempt.result_hash!,deliveryDigest:hashBytes(content),rules,content,nativeLoading:'unverified' as const};}
function canonicalPath(path:string):string{const absolute=resolve(path);try{return realpathSync(absolute);}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT'||dirname(absolute)===absolute)throw new Error('application_path_forbidden',{cause:error});return join(canonicalPath(dirname(absolute)),basename(absolute));}}
export class ApplicationCoordinator{
 constructor(private readonly store:Store,private readonly protectedPaths:readonly string[]|(()=>readonly string[])=[]){store.execute("UPDATE harness_application_attempts SET state='failed',reason_code='application_restart_interrupted' WHERE state IN ('awaiting_session','applying','verifying')",[]);}
 workspace(taskId:string,directory:string){const row=marker(this.store,taskId),workspace=inspectApplicationWorkspace(projectRoot(this.store,row.project_id),directory);return {...workspace,digest:hashBytes(JSON.stringify(workspace))};}
 status(taskId:string){if(!this.store.get('SELECT 1 FROM harness_application_tasks WHERE task_id=?',[taskId])&&applicationRequired(this.store,taskId))return {state:'failed',jobId:null,epoch:0,reason:'application_integrity_unverified',workspace:null,launchState:'not_requested',identity:'unavailable'};const row=marker(this.store,taskId);const attempt=row.current_job?this.store.get<Attempt>('SELECT * FROM harness_application_attempts WHERE id=?',[row.current_job]):undefined;let selectedProduct:string|null=null;let workspace:string|null=null,reason=attempt?.reason_code??null,state=attempt?.state??'awaiting_application';try{if(row.current_job&&!attempt)throw new Error('application_managed_retired');if(attempt){const data=current(this.store,taskId);workspace=data.context.workspace.root;selectedProduct=data.context.product;if(attempt.state==='applied')verifyFiles(data);}else workspace=loadProcedure(this.store,row).origin;}catch(error){state='failed';reason=error instanceof Error&&/^application_[a-z_]+$/.test(error.message)?error.message:'application_integrity_unverified';}return {state,jobId:attempt?.id??null,epoch:row.epoch,reason,workspace,launchState:attempt?.launch_state??'not_requested',identity:attempt?.identity_hash?'verified_metadata':'unavailable',product:selectedProduct};}
 private inactive(taskId:string){const task=this.store.get<{state:string}>('SELECT state FROM tasks WHERE id=?',[taskId]);if(!task||['active','finalized'].includes(task.state)||this.store.get("SELECT 1 FROM session_bindings WHERE task_id=? AND state='observing' UNION ALL SELECT 1 FROM codex_workflow_runs WHERE task_id=? AND state='running' UNION ALL SELECT 1 FROM claude_workflow_runs WHERE task_id=? AND state='running'",[taskId,taskId,taskId]))throw new Error('workflow_run_active');const prior=this.store.get<{first_connected_at:string|null;state:string}>('SELECT first_connected_at,state FROM external_preparations WHERE task_id=?',[taskId]);if(prior?.first_connected_at&&prior.state!=='released')throw new Error('external_stop_acknowledgement_required');}
 prepareHandoff(taskId:string,input:ApplicationSelection){const selection=ApplicationSelectionSchema.parse(input),row=marker(this.store,taskId);this.inactive(taskId);const procedure=loadProcedure(this.store,row),workspace=inspectApplicationWorkspace(procedure.origin,selection.workspace);if(hashBytes(JSON.stringify(workspace))!==selection.workspaceDigest)throw new Error('application_preview_changed');
 const task=this.store.get<{metadata:string}>('SELECT metadata FROM tasks WHERE id=?',[taskId])!;const product=(JSON.parse(task.metadata) as {product:string}).product;if(product!=='synthetic'&&product!==selection.product)throw new Error('application_product_mismatch');
 const old=row.current_job?this.store.get<Attempt>('SELECT * FROM harness_application_attempts WHERE id=?',[row.current_job]):undefined;
 if(old&&['awaiting_session','applying','applied'].includes(old.state)){const data=current(this.store,taskId);if(canonicalJson(data.context.workspace)!==canonicalJson(workspace)||data.context.product!==selection.product)throw new Error('application_job_active');if(old.state==='applied')verifyFiles(data);return data.context;}
 const assignment=this.store.get<{variant_id:string}>('SELECT variant_id FROM comparison_assignments WHERE task_id=?',[taskId]);if(!assignment)throw new Error('task_not_assigned');
 let priorOutputs:{path:string;sha256:string|null}[]=[];if(old?.result_hash){const data=current(this.store,taskId);priorOutputs=resultFor(data).outputs.map(({path,sha256})=>({path,sha256}));}
 const context=ApplicationContextSchema.parse({attempt_id:randomUUID(),task_id:taskId,project_id:row.project_id,product:selection.product,variant_id:assignment.variant_id,bundle_path:procedure.bundlePath,bundle_hash:procedure.bundleHash,workspace,epoch:row.epoch+1,prior_outputs:priorOutputs});const bytes=Buffer.from(canonicalJson(context));durablePrivateBytes(procedure.origin,`${privatePath(taskId)}/${context.attempt_id}/context.json`,bytes);
 this.store.immediateTransaction(()=>{marker(this.store,taskId);const owner=this.store.get<{task_id:string}>('SELECT task_id FROM external_surface_leases WHERE surface_key=?',[hashBytes(workspace.root)]);if(owner&&owner.task_id!==taskId)throw new Error('external_surface_busy');this.store.execute('DELETE FROM external_surface_leases WHERE task_id=?',[taskId]);this.store.execute('INSERT INTO external_surface_leases(surface_key,task_id) VALUES(?,?)',[hashBytes(workspace.root),taskId]);this.store.execute("INSERT INTO harness_application_attempts(id,task_id,state,context_hash,epoch) VALUES(?,?,'awaiting_session',?,?)",[context.attempt_id,taskId,hashBytes(bytes),context.epoch]);this.store.execute('UPDATE harness_application_tasks SET current_job=? WHERE task_id=?',[context.attempt_id,taskId]);});return context;
 }
 context(taskId:string,attemptId:string){const data=current(this.store,taskId);if(data.attempt.id!==attemptId||!['awaiting_session','applying','applied'].includes(data.attempt.state))throw new Error('application_attempt_stale');owned(this.store,data);if(data.attempt.state==='applied')verifyFiles(data);const bundle=readHarness(data.procedure.origin,data.procedure.bundlePath);return {...data.context,origin_root:data.procedure.origin,artifacts:bundle.artifacts.map(artifact=>({artifact_id:artifact.artifact_id,role:artifact.role,path:join(data.procedure.origin,artifact.path),sha256:artifact.sha256})),common:data.procedure.common??[],file_verification:'reported_file_set_only',tool_evidence:'agent_reported',native_permissions:'native_window'};}
 private live(taskId:string,attemptId:string){const data=current(this.store,taskId);this.inactive(taskId);if(data.attempt.id!==attemptId||!['awaiting_session','applying'].includes(data.attempt.state))throw new Error('application_attempt_stale');owned(this.store,data);return data;}
 private safeFile(data:ReturnType<typeof current>,path:string){applicationPath(path);const absolute=resolve(data.context.workspace.root,path);const protectedPaths=[this.store.filename,...(typeof this.protectedPaths==='function'?this.protectedPaths():this.protectedPaths)].filter(p=>p!==':memory:').map(canonicalPath).flatMap(p=>[p,p+'-wal',p+'-shm',p+'-journal']);if(protectedPaths.some(p=>absolute.toLowerCase()===p.toLowerCase()||absolute.toLowerCase().startsWith(p.toLowerCase()+'/')))throw new Error('application_path_forbidden');try{if(lstatSync(absolute).nlink!==1)throw new Error('application_path_forbidden');}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}return optionalApplicationBytes(data.context.workspace.root,path);}
 checkpoint(taskId:string,input:z.infer<typeof ApplicationCheckpointSchema>){const request=ApplicationCheckpointSchema.parse(input),data=this.live(taskId,request.attempt_id);if(new Set(request.paths.map(path=>path.toLowerCase())).size!==request.paths.length)throw new Error('application_scope_invalid');
 return request.paths.map(path=>{const pathHash=hashBytes(path.toLowerCase()),existing=this.store.get<Checkpoint>('SELECT * FROM harness_application_checkpoints WHERE attempt_id=? AND path_hash=?',[data.attempt.id,pathHash]);if(existing){const record=this.checkpointRecord(data,existing);if(record.path!==path)throw new Error('application_checkpoint_invalid');const actual=this.safeFile(data,path);if((actual===null?null:hashBytes(actual))!==record.before_hash)throw new Error('application_preimage_changed');return {path,checkpoint_id:existing.id,before_hash:existing.before_hash};}
 if(this.store.get<{count:number}>('SELECT count(*) AS count FROM harness_application_checkpoints WHERE attempt_id=?',[data.attempt.id])!.count>=256)throw new Error('application_scope_invalid');const before=this.safeFile(data,path),id=randomUUID(),beforeHash=before===null?null:hashBytes(before);const beforeFile=before===null?null:`checkpoints/${id}.bytes`;if(beforeFile)durablePrivateBytes(data.procedure.origin,`${data.directory}/${beforeFile}`,before!);const bytes=Buffer.from(canonicalJson({path,before_hash:beforeHash,before_file:beforeFile}));durablePrivateBytes(data.procedure.origin,`${data.directory}/checkpoints/${id}.json`,bytes);this.store.execute('INSERT INTO harness_application_checkpoints(id,attempt_id,path_hash,before_hash,record_hash) VALUES(?,?,?,?,?)',[id,data.attempt.id,pathHash,beforeHash,hashBytes(bytes)]);this.store.execute("UPDATE harness_application_attempts SET state='applying' WHERE id=?",[data.attempt.id]);return {path,checkpoint_id:id,before_hash:beforeHash};});
 }
 private checkpointRecord(data:ReturnType<typeof current>,checkpoint:Checkpoint){const bytes=readRepositoryFile(data.procedure.origin,`${data.directory}/checkpoints/${checkpoint.id}.json`);if(hashBytes(bytes)!==checkpoint.record_hash)throw new Error('application_checkpoint_invalid');const record=checkpointSchema.parse(readStrictJson(bytes));if(record.before_hash!==checkpoint.before_hash)throw new Error('application_checkpoint_invalid');return record;}
 report(taskId:string,input:z.infer<typeof ApplicationReportSchema>){const report=ApplicationReportSchema.parse(input);let data=current(this.store,taskId);const reportHash=hashBytes(canonicalJson(report));if(data.attempt.id!==report.attempt_id)throw new Error('application_attempt_stale');if(data.attempt.state==='applied'){if(resultFor(data).report_hash!==reportHash)throw new Error('application_report_conflict');verifyFiles(data);return this.status(taskId);}data=this.live(taskId,report.attempt_id);if(report.bundle_hash!==data.procedure.bundleHash)throw new Error('application_input_changed');if(new Set(report.outputs.map(output=>output.path.toLowerCase())).size!==report.outputs.length||new Set(report.checks.map(check=>check.check_id)).size!==report.checks.length)throw new Error('application_scope_invalid');
 for(const output of report.outputs){const checkpoint=this.store.get<Checkpoint>('SELECT * FROM harness_application_checkpoints WHERE id=? AND attempt_id=?',[output.checkpoint_id,data.attempt.id]);if(!checkpoint||this.checkpointRecord(data,checkpoint).path!==output.path)throw new Error('application_checkpoint_invalid');const actual=this.safeFile(data,output.path);if((actual===null?null:hashBytes(actual))!==output.sha256)throw new Error('application_output_changed');}
 const changed=new Set(report.outputs.map(output=>output.path));const outputs=[...data.context.prior_outputs.filter(output=>!changed.has(output.path)).map(output=>({...output,checkpoint_id:null})),...report.outputs];if(outputs.length>256)throw new Error('application_scope_invalid');for(const output of outputs)if(outputDigest(data.context.workspace.root,output.path)!==output.sha256)throw new Error('application_output_changed');
 const result=resultSchema.parse({outputs,checks:report.checks.map(check=>({...check,evidence:'agent_reported'})),report_hash:reportHash}),bytes=Buffer.from(canonicalJson(result));durablePrivateBytes(data.procedure.origin,`${data.directory}/result.json`,bytes);
 this.store.immediateTransaction(()=>{this.live(taskId,report.attempt_id);this.store.execute("UPDATE harness_application_attempts SET state='applied',result_hash=?,completed_at=?,reason_code=? WHERE id=?",[hashBytes(bytes),new Date().toISOString(),result.checks.length&&result.checks.every(check=>check.outcome==='passed')?null:'application_checks_incomplete',data.attempt.id]);this.store.execute('UPDATE harness_application_tasks SET epoch=? WHERE task_id=?',[data.attempt.epoch,taskId]);});return this.status(taskId);
 }
 review(taskId:string){const data=current(this.store,taskId),result=resultFor(data);const changes=result.outputs.map(output=>{let before:Buffer|null=null,baseline='missing';if(output.checkpoint_id){const checkpoint=this.store.get<Checkpoint>('SELECT * FROM harness_application_checkpoints WHERE id=? AND attempt_id=?',[output.checkpoint_id,data.attempt.id]);if(!checkpoint)throw new Error('application_checkpoint_invalid');const record=this.checkpointRecord(data,checkpoint);if(record.before_file){before=readRepositoryFile(data.procedure.origin,`${data.directory}/${record.before_file}`);if(hashBytes(before)!==record.before_hash)throw new Error('application_checkpoint_invalid');}baseline='checkpoint';}const after=this.safeFile(data,output.path);const text=(bytes:Buffer|null)=>bytes===null?null:!bytes.includes(0)&&Buffer.from(bytes.toString('utf8')).equals(bytes)?bytes.toString('utf8'):null;return {path:output.path,baseline,before:text(before),after:text(after),before_hash:before===null?null:hashBytes(before),actual_hash:after===null?null:hashBytes(after),verified:(after===null?null:hashBytes(after))===output.sha256};});return {jobId:data.attempt.id,workspace:data.context.workspace,changes,checks:result.checks,scope:'reported_file_set_only'};}
 registerIdentity(taskId:string,attemptId:string,identity:VerifiedSessionIdentity){const data=this.live(taskId,attemptId);if(identity.product!==data.context.product||identity.cwd!==data.context.workspace.root||identity.parentSessionId!==null)throw new Error('binding_identity_mismatch');const hash=identityHash(identity.product,identity.sessionId);if(data.attempt.identity_hash&&data.attempt.identity_hash!==hash)throw new Error('binding_identity_mismatch');this.store.immediateTransaction(()=>{this.live(taskId,attemptId);this.store.execute('INSERT OR IGNORE INTO harness_application_roles(identity_hash,attempt_id,parent_hash) VALUES(?,?,NULL)',[hash,attemptId]);this.store.execute('UPDATE harness_application_attempts SET identity_hash=? WHERE id=?',[hash,attemptId]);});return {identity:'verified_metadata',measurement:false};}
 launchContext(taskId:string,origin:string){const selected=current(this.store,taskId);const data=this.live(taskId,selected.attempt.id);const packaged=fileURLToPath(new URL('./skills/harness-apply/SKILL.md',import.meta.url));const skill=existsSync(packaged)?packaged:fileURLToPath(new URL('../skills/harness-apply/SKILL.md',import.meta.url));return {attemptId:data.attempt.id,workspace:data.context.workspace.root,product:data.context.product,prompt:`Use harness-apply. Read ${JSON.stringify(skill)} and perform the procedure yourself in this application-only session. Context: ${JSON.stringify({origin,task_id:taskId,attempt_id:data.attempt.id,workspace:data.context.workspace.root,bundle_hash:data.procedure.bundleHash})}. Native permissions apply. Do not connect this session for measurement.`};}
 async open(taskId:string,origin:string,environment:LaunchEnvironment={}){const context=this.launchContext(taskId,origin),data=this.live(taskId,context.attemptId);if(data.attempt.launch_state!=='not_requested')return this.status(taskId);if(!getApplicationLaunchCapability(context.product,environment).available)throw new Error('application_launch_unavailable');this.store.execute("UPDATE harness_application_attempts SET launch_state='open_requested' WHERE id=?",[data.attempt.id]);const result=await openApplicationSession(context,{...environment,directory:join(data.procedure.origin,data.directory)});marker(this.store,taskId);this.store.execute('UPDATE harness_application_attempts SET launch_state=? WHERE id=? AND task_id=?',[result.state,data.attempt.id,taskId]);return this.status(taskId);}
 handoff(taskId:string,origin:string){const data=current(this.store,taskId);let readiness='application_required';try{assertAppliedHarness(this.store,taskId);readiness=data.attempt.identity_hash?'native_loading_and_source_qualification_required':'application_identity_unavailable';}catch(error){if(error instanceof Error)readiness=error.message;}return {task_id:taskId,workspace:data.context.workspace.root,variant_id:data.context.variant_id,bundle_hash:data.context.bundle_hash,readiness,native_loading:'unverified',guidance:`Start a separate fresh ${data.context.product} session in ${JSON.stringify(data.context.workspace.root)}. Read the generated instructions, then use harness-connect with origin ${origin} and task ${taskId}. Do not use the applying session. Collection requires supported native identity, loading evidence and source admission.`,connect_context:{origin,task_id:taskId,product:data.context.product}};}
 cancel(taskId:string){const data=current(this.store,taskId);this.inactive(taskId);this.store.execute("UPDATE harness_application_attempts SET state='abandoned',reason_code='application_abandoned' WHERE id=?",[data.attempt.id]);return this.status(taskId);}
 close(){/* External native sessions are never controlled or stopped here. */}
}
export function applicationEvidence(store:Store,taskId:string){let state='failed',procedureHash:string|null=null,outputHash:string|null=null,epoch=0;try{const row=marker(store,taskId);epoch=row.epoch;procedureHash=loadProcedure(store,row).bundleHash;const attempt=row.current_job?store.get<Attempt>('SELECT * FROM harness_application_attempts WHERE id=?',[row.current_job]):undefined;state=attempt?.state??(row.current_job?'failed':'awaiting_application');outputHash=attempt?.result_hash??null;}catch{/* Preserve a fail-closed opaque application fence. */}return {schema_version:2,mode:'agent_applied' as const,procedure_bundle_hash:procedureHash,approved_output_manifest_hash:outputHash,native_delivery_digest:null,epoch,state};}
